artifact_location: file:///D:/Learning/mlops/chest_dieses/Chest-Disease-Classification-from-Chest-CT-Scan-Image-main-20241112T054341Z-001/Chest-Disease-Classification-from-Chest-CT-Scan-Image-main/research/MLFLOW_TRACKING_URI/0
creation_time: 1731409115851
experiment_id: '0'
last_update_time: 1731409115851
lifecycle_stage: active
name: Default
